Delete http://localhost:3003/api/bloglists/62613ba045e7426e0df9592a
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1aDMiLCJpZCI6IjYyNWJmZTc5YmVkNWZiYTNhZTU0MjM2NyIsImlhdCI6MTY1MDg4NTAyMn0.D6krfdKWNA6jc7oVnJnXaFkXBHAE9IKIbGXDjI94PDM