DELETE http://localhost:3001/api/bloglists/625f13178b7ab32c39d0685c
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MjVlOWU4NzZjYjJhZWYyMjY2ZDIzMjgiLCJpYXQiOjE2NTAzOTc5MDMsImV4cCI6MTY1MDQwMTUwM30.htbeMRfjLNS7kZBdDILcKrlNJAyqCztjoVhkJByBEZQ
