DELETE http://localhost:3001/api/bloglists/625f112975a00f91fd68b852
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1aDMiLCJpZCI6IjYyNWJmZTc5YmVkNWZiYTNhZTU0MjM2NyIsImlhdCI6MTY1MDM5ODYyMSwiZXhwIjoxNjUwNDAyMjIxfQ.6bdRY6f5eVTQDTxql01ZYNjCC_ROfmJM3BDheftjjTo