POST http://localhost:3001/api/bloglists
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MjVlOWU4NzZjYjJhZWYyMjY2ZDIzMjgiLCJpYXQiOjE2NTAzOTc5MDMsImV4cCI6MTY1MDQwMTUwM30.htbeMRfjLNS7kZBdDILcKrlNJAyqCztjoVhkJByBEZQ

{
    "author": "Kauko Kärhä",
    "title": "Kaukonäön puolet",
    "likes": 0,
    "url": "http://www.kaukonäönKärhä.fi",
    "id": "625e9e876cb2aef2266d2328"
}