POST http://localhost:3001/api/patients/hji-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/application/json

{
    "date": "2018-01-02",
    "type": "Hospital",
    "specialist": "MD House",
    "diagnosisCodes": [
  "S62.5"
  ],
  "description": "Healing time appr. 15 weeks. patient doesn't remember how he got the injury.",
  "discharge": {
    "date": "2018-02-16",
    "criteria": "Thumb has healed."
  }
}